export const RouterUrl = {
  Store: '/toolkit/store',
  Assets: '/toolkit/assets',
  Generate: '/toolkit/generate',
  ImageGenerate: '/toolkit/image-generate',
  VideoGenerate: '/toolkit/video-generate',
  Business: '/business',
  Cart: '/toolkit/cart',
  Checkout: '/toolkit/checkout',
  UserSubscription: '/user/subscription',
  UserCreditHistory: '/user/credit-history',
  UserMyPrompt: '/user/my-prompt',
  UserOrderHistory: '/user/order-history',
  UserManageAccount: '/user/manage-account',
};
